# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\JenIKs\PycharmProjects\QTCalc\front.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PySide2 import QtCore, QtGui, QtWidgets
from PySide2.QtCore import (QCoreApplication, QPropertyAnimation, QDate, QDateTime, QMetaObject, QObject, QPoint, QRect, QSize, QTime, QUrl, Qt, QEvent)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont, QFontDatabase, QIcon, QKeySequence, QLinearGradient, QPalette, QPainter, QPixmap, QRadialGradient)
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 500)
        MainWindow.setMinimumSize(QtCore.QSize(400, 500))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        MainWindow.setPalette(palette)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("background-color:#ececec;\n"
" border-color: rgb(236, 236, 236);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_pages)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.gridLayout.addWidget(self.pushButton_29, 6, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border: none;\n"
"background-color: rgb(236, 236, 236)\n"
"")
        self.lineEdit_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 0, 1, 4)
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.gridLayout.addWidget(self.pushButton_32, 7, 0, 1, 1)
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.gridLayout.addWidget(self.pushButton_30, 7, 1, 1, 1)
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.gridLayout.addWidget(self.pushButton_34, 6, 0, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_5.sizePolicy().hasHeightForWidth())
        self.lineEdit_5.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(172, 172, 172))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(236, 236, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.lineEdit_5.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setStyleSheet("border: none;\n"
"background-color: rgb(236, 236, 236)")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 0, 1, 4)
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.gridLayout.addWidget(self.pushButton_33, 6, 1, 1, 1)
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #fafafa;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.gridLayout.addWidget(self.pushButton_28, 6, 2, 1, 1)
        self.pushButton_46 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_46.sizePolicy().hasHeightForWidth())
        self.pushButton_46.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_46.setObjectName("pushButton_46")
        self.gridLayout.addWidget(self.pushButton_46, 4, 2, 1, 1)
        self.pushButton_41 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_41.sizePolicy().hasHeightForWidth())
        self.pushButton_41.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.gridLayout.addWidget(self.pushButton_41, 3, 0, 1, 1)
        self.pushButton_42 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_42.sizePolicy().hasHeightForWidth())
        self.pushButton_42.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.gridLayout.addWidget(self.pushButton_42, 3, 1, 1, 1)
        self.pushButton_39 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_39.sizePolicy().hasHeightForWidth())
        self.pushButton_39.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.gridLayout.addWidget(self.pushButton_39, 2, 3, 1, 1)
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_36.sizePolicy().hasHeightForWidth())
        self.pushButton_36.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.gridLayout.addWidget(self.pushButton_36, 2, 0, 1, 1)
        self.pushButton_40 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_40.sizePolicy().hasHeightForWidth())
        self.pushButton_40.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.gridLayout.addWidget(self.pushButton_40, 3, 2, 1, 1)
        self.pushButton_45 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_45.sizePolicy().hasHeightForWidth())
        self.pushButton_45.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_45.setObjectName("pushButton_45")
        self.gridLayout.addWidget(self.pushButton_45, 4, 1, 1, 1)
        self.pushButton_37 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_37.sizePolicy().hasHeightForWidth())
        self.pushButton_37.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.gridLayout.addWidget(self.pushButton_37, 2, 1, 1, 1)
        self.pushButton_47 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_47.sizePolicy().hasHeightForWidth())
        self.pushButton_47.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_47.setObjectName("pushButton_47")
        self.gridLayout.addWidget(self.pushButton_47, 4, 3, 1, 1)
        self.pushButton_38 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_38.sizePolicy().hasHeightForWidth())
        self.pushButton_38.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.gridLayout.addWidget(self.pushButton_38, 2, 2, 1, 1)
        self.pushButton_48 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_48.setObjectName("pushButton_48")
        self.gridLayout.addWidget(self.pushButton_48, 5, 0, 1, 1)
        self.pushButton_44 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_44.sizePolicy().hasHeightForWidth())
        self.pushButton_44.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.gridLayout.addWidget(self.pushButton_44, 4, 0, 1, 1)
        self.pushButton_43 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_43.sizePolicy().hasHeightForWidth())
        self.pushButton_43.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.gridLayout.addWidget(self.pushButton_43, 3, 3, 1, 1)
        self.pushButton_49 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_49.setObjectName("pushButton_49")
        self.gridLayout.addWidget(self.pushButton_49, 5, 1, 1, 1)
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_35.sizePolicy().hasHeightForWidth())
        self.pushButton_35.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f0f0f0;\n"
"   border: 1px  solid;\n"
"   border-color: #e6e6e6;\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.gridLayout.addWidget(self.pushButton_35, 5, 3, 1, 1)
        self.pushButton_50 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_50.sizePolicy().hasHeightForWidth())
        self.pushButton_50.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_50.setObjectName("pushButton_50")
        self.gridLayout.addWidget(self.pushButton_50, 5, 2, 1, 1)
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #A8C9EA;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.gridLayout.addWidget(self.pushButton_27, 7, 3, 1, 1)
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_pages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton {\n"
"   color: rgb(0, 0, 0);\n"
"   background-color: #f8f8f8;\n"
"   border: 1px  solid;\n"
"   border-color: rgb(236, 236, 236);\n"
"}\n"
"QPushButton:hover {\n"
"   background-color: #e3e3e3;\n"
"}\n"
"QPushButton:pressed {\n"
"   background-color: #d6d6d6;\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.gridLayout.addWidget(self.pushButton_31, 7, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_29.setText(_translate("MainWindow", "+"))
        self.lineEdit_4.setText(_translate("MainWindow", "0"))
        self.pushButton_32.setText(_translate("MainWindow", "±"))
        self.pushButton_30.setText(_translate("MainWindow", "0"))
        self.pushButton_34.setText(_translate("MainWindow", "1"))
        self.pushButton_33.setText(_translate("MainWindow", "2"))
        self.pushButton_28.setText(_translate("MainWindow", "3"))
        self.pushButton_46.setText(_translate("MainWindow", "9"))
        self.pushButton_41.setText(_translate("MainWindow", "1/x"))
        self.pushButton_42.setText(_translate("MainWindow", "xⁿ"))
        self.pushButton_39.setText(_translate("MainWindow", "<"))
        self.pushButton_36.setText(_translate("MainWindow", "+-"))
        self.pushButton_40.setText(_translate("MainWindow", "√x"))
        self.pushButton_45.setText(_translate("MainWindow", "8"))
        self.pushButton_37.setText(_translate("MainWindow", "CE"))
        self.pushButton_47.setText(_translate("MainWindow", "x"))
        self.pushButton_38.setText(_translate("MainWindow", "C"))
        self.pushButton_48.setText(_translate("MainWindow", "4"))
        self.pushButton_44.setText(_translate("MainWindow", "7"))
        self.pushButton_43.setText(_translate("MainWindow", "÷"))
        self.pushButton_49.setText(_translate("MainWindow", "5"))
        self.pushButton_35.setText(_translate("MainWindow", "-"))
        self.pushButton_50.setText(_translate("MainWindow", "6"))
        self.pushButton_27.setText(_translate("MainWindow", "="))
        self.pushButton_31.setText(_translate("MainWindow", "."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
