from all_modules import *


class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.show()
        Number.numbers(self)
        Operatsion.oper(self)

    def resizeEvent(self, event):
        width = self.size().width()
        height = self.size().height()
        if 839 >= width >= 490 or 839 >= height >= 570:
            self.ui.pushButton_30.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_34.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_33.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_28.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_48.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_49.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_50.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_44.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_45.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_46.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_36.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_37.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_38.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_39.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_40.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_41.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_42.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_43.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_47.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_35.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_29.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_27.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_31.setFont(QFont('Segoe UI', 19))
            self.ui.pushButton_32.setFont(QFont('Segoe UI', 19))
            self.ui.lineEdit_4.setFont(QFont('Segoe UI', 36, QtGui.QFont.Bold))
            self.ui.lineEdit_5.setFont(QFont('Segoe UI', 23, QtGui.QFont.Bold))

        elif width >= 840 and height >= 840:
            self.ui.pushButton_30.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_34.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_33.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_28.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_48.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_49.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_50.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_44.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_45.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_46.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_36.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_37.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_38.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_39.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_40.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_41.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_42.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_43.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_47.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_35.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_29.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_27.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_31.setFont(QFont('Segoe UI', 24))
            self.ui.pushButton_32.setFont(QFont('Segoe UI', 24))
            self.ui.lineEdit_4.setFont(QFont('Segoe UI', 41, QtGui.QFont.Bold))
            self.ui.lineEdit_5.setFont(QFont('Segoe UI', 28, QtGui.QFont.Bold))
        else:
            self.ui.pushButton_30.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_34.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_33.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_28.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_48.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_49.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_50.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_44.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_45.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_46.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_36.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_37.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_38.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_39.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_40.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_41.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_42.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_43.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_47.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_35.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_29.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_27.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_31.setFont(QFont('Segoe UI', 16))
            self.ui.pushButton_32.setFont(QFont('Segoe UI', 16))
            self.ui.lineEdit_4.setFont(QFont(QFont('Segoe UI', 33, QtGui.QFont.Bold)))
            self.ui.lineEdit_5.setFont(QFont(QFont('Segoe UI', 20, QtGui.QFont.Bold)))


if __name__ == "__main__":
    app = QApplication(sys.argv)
    window = MainWindow()

    sys.exit(app.exec_())
